//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ewk_server_v2 {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ewk_server_v2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
		
		       /// <summary>
        ///   [1560bd]{0}: [36454f]{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Chatting_Color {
            get {
                return ResourceManager.GetString("Chat_Chatting_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ff4f00]{0}[1560bd]님께서 대결 준비 중입니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Game_Ready_Notification {
            get {
                return ResourceManager.GetString("Chat_Game_Ready_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]이제 게임 시작을 시작합니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Game_Start_Notification {
            get {
                return ResourceManager.GetString("Chat_Game_Start_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]이제 게임 시작이 가능합니다. &quot;준비&quot; 버튼을 눌러주세요.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Join_Full {
            get {
                return ResourceManager.GetString("Chat_Join_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ff4f00]{0}[1560bd]님께서 입장하셨습니다.({1}/2)[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Join_User {
            get {
                return ResourceManager.GetString("Chat_Join_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]E.W.K 2인 대전방에 오신것을 환영합니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Join_Welcome {
            get {
                return ResourceManager.GetString("Chat_Join_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ff4f00]{0}[1560bd]께서 퇴장하셨습니다.({1}/2)[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat_Leave_User {
            get {
                return ResourceManager.GetString("Chat_Leave_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]게임이 끝났습니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Game_End {
            get {
                return ResourceManager.GetString("Game_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]아직 정원이 다 차지 않았습니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Game_Open_Error_NotCompleteRoom {
            get {
                return ResourceManager.GetString("Game_Open_Error_NotCompleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [1560bd]게임 시작까지 {0}초 남았습니다.[36454f]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Game_Start_Count {
            get {
                return ResourceManager.GetString("Game_Start_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}님께서 로그인 하셨습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Login_Open_Message {
            get {
                return ResourceManager.GetString("Login_Open_Message", resourceCulture);
            }
        }
    }
}
